### ISSUE TITLE
遇到一个报错

### ISSUE THREAD

**Issue by poembro** [aceld/zinx#88]
```
 goroutine 42866 [select]:
 github.com/aceld/zinx/znet.(*Connection).StartWriter(0xc0004d8e10)
 /data/web/golang/pkg/mod/github.com/aceld/zinx@v1.0.0/znet/connection.go:68 +0x297
 created by github.com/aceld/zinx/znet.(*Connection).Start
 /data/web/golang/pkg/mod/github.com/aceld/zinx@v1.0.0/znet/connection.go:158 +0xa5

 goroutine 42801 [IO wait]:
 internal/poll.runtime_pollWait(0x7fb04d6806e8, 0x72, 0xffffffffffffffff)
 /usr/local/go/src/runtime/netpoll.go:184 +0x55
 internal/poll.(*pollDesc).wait(0xc000176018, 0x72, 0x0, 0x8, 0xffffffffffffffff)
 /usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
 internal/poll.(*pollDesc).waitRead(...)
 /usr/local/go/src/internal/poll/fd_poll_runtime.go:92
 internal/poll.(*FD).Read(0xc000176000, 0xc00020e7a8, 0x8, 0x8, 0x0, 0x0, 0x0)
 /usr/local/go/src/internal/poll/fd_unix.go:169 +0x1cf
 net.(*netFD).Read(0xc000176000, 0xc00020e7a8, 0x8, 0x8, 0x20, 0x8, 0x455ca0)
 /usr/local/go/src/net/fd_unix.go:202 +0x4f
 net.(*conn).Read(0xc0000104a8, 0xc00020e7a8, 0x8, 0x8, 0x0, 0x0, 0x0)
 /usr/local/go/src/net/net.go:184 +0x68
 io.ReadAtLeast(0xa6e280, 0xc0000104a8, 0xc00020e7a8, 0x8, 0x8, 0x8, 0x9, 0x0, 0x0)
 /usr/local/go/src/io/io.go:310 +0x87
 io.ReadFull(...)
 /usr/local/go/src/io/io.go:329
 github.com/aceld/zinx/znet.(*Connection).StartReader(0xc0004d8e10)
 /data/web/golang/pkg/mod/github.com/aceld/zinx@v1.0.0/znet/connection.go:111 +0x251
 created by github.com/aceld/zinx/znet.(*Connection).Start
 /data/web/golang/pkg/mod/github.com/aceld/zinx@v1.0.0/znet/connection.go:156 +0x83
```

**Comment by aceld** [comment]
能把最近的或者全部的堆栈信息打出来么，感觉开的go的数量太多了。是不是开的链接太多，可以限定一下最大链接数量。

**Comment by wecane** [comment]
出现了相同的错误，目前还不知道什么原因。
